# Generated by Django 3.0.4 on 2020-03-17 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_cat', models.CharField(max_length=350)),
                ('raw_sub_cat', models.CharField(max_length=300)),
                ('quantity', models.FloatField(verbose_name='raw_material_quantity')),
                ('mode', models.CharField(choices=[('kg', 'KiloGrams'), ('ltr', 'Litres')], max_length=120)),
                ('density', models.FloatField(verbose_name='raw-material_denisty')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='product name')),
                ('quantity_prod', models.FloatField(verbose_name='ProdutionQuantity')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.RawMaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField(verbose_name='bill_number')),
                ('dispatch_status', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.ProductionStage')),
            ],
        ),
    ]
