# Generated by Django 3.0.4 on 2020-05-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500, verbose_name='Raw-Material-Name')),
                ('date', models.DateField(verbose_name='raw-material_date')),
                ('quantity', models.FloatField(verbose_name='raw_material_quantity')),
                ('mode', models.CharField(choices=[('kg', 'KiloGrams'), ('ltr', 'Litres')], max_length=120)),
                ('density', models.FloatField(verbose_name='raw-material_denisty')),
                ('selected', models.BooleanField(default=False)),
                ('rate', models.FloatField(verbose_name='raw_material_rate')),
                ('supplier', models.CharField(max_length=300, verbose_name='supplier_name')),
            ],
            options={
                'verbose_name': 'raw material',
                'verbose_name_plural': 'raw materials',
                'ordering': ('date', 'name', 'quantity'),
            },
        ),
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prod', models.DateField(verbose_name='production_date')),
                ('name', models.CharField(max_length=350, verbose_name='product name')),
                ('quantity_prod', models.FloatField(verbose_name='ProdutionQuantity')),
                ('selected', models.BooleanField(default=False)),
                ('raw_materials', models.ManyToManyField(to='StockApp.RawMaterial')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('date_prod', 'name', 'quantity_prod'),
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_dispatch', models.DateField(verbose_name='date_of_dispatch')),
                ('bill_no', models.IntegerField(verbose_name='bill_number')),
                ('dispatch_status', models.BooleanField(default=True, verbose_name='dispatch_status')),
                ('products', models.ManyToManyField(to='StockApp.ProductionStage')),
            ],
            options={
                'verbose_name': 'dispatch',
                'verbose_name_plural': 'dispatches',
                'ordering': ('date_dispatch', 'bill_no'),
            },
        ),
    ]
