# Generated by Django 3.0.4 on 2020-03-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='date_dispatch',
            field=models.DateField(auto_now=True, verbose_name='date_of_dispatch'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='date_prod',
            field=models.DateField(auto_now=True, verbose_name='production_date'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='raw-material_date'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='name',
            field=models.CharField(default=None, max_length=500, verbose_name='Raw-Material-Name'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
