# Generated by Django 3.0.4 on 2020-04-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0002_auto_20200331_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstage',
            name='ratio1',
            field=models.IntegerField(default=0, verbose_name='ratio1'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='ratio2',
            field=models.IntegerField(default=0, verbose_name='ratio2'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='ratio3',
            field=models.IntegerField(default=0, verbose_name='ratio3'),
        ),
    ]
