# Generated by Django 3.0.4 on 2020-04-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0003_auto_20200404_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionstage',
            name='ratio1',
        ),
        migrations.RemoveField(
            model_name='productionstage',
            name='ratio2',
        ),
        migrations.RemoveField(
            model_name='productionstage',
            name='ratio3',
        ),
    ]
